"use strict";
const rupiahFormatter=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",minimumFractionDigits:0});
const waktuFormatter=new Intl.DateTimeFormat("id-ID",{dateStyle:"short",timeStyle:"medium"});
let busy=false;
function rupiah(v){return rupiahFormatter.format(Number(v)||0)}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function showLoading(v){document.getElementById("loadingOverlay")?.classList.toggle("show",v)}
function renderKategori(id,items,totalId){const el=document.getElementById(id); if(!items?.length){el.innerHTML='<tr><td colspan="4" class="text-center text-muted py-4">Belum ada data</td></tr>';return} el.innerHTML=items.map((x,i)=>`<tr><td>${i+1}</td><td class="fw-semibold">${esc(x.kategori)}</td><td class="text-center">${x.transaksi}</td><td class="text-end fw-bold">${rupiah(x.jumlah)}</td></tr>`).join(""); setText(totalId,rupiah(items.reduce((a,x)=>a+Number(x.jumlah||0),0)))}
function renderRecent(items){const el=document.getElementById("transaksiTerakhir");if(!items?.length){el.innerHTML='<tr><td colspan="6" class="text-center text-muted py-4">Belum ada transaksi</td></tr>';return} el.innerHTML=items.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.tanggal)}</td><td><span class="badge ${x.jenis==='MASUK'?'bg-success':'bg-danger'}">${esc(x.jenis)}</span></td><td>${esc(x.kategori)}</td><td>${esc(x.keterangan)}</td><td class="text-end fw-bold ${x.jenis==='MASUK'?'text-success':'text-danger'}">${rupiah(x.nominal)}</td></tr>`).join("")}
async function loadDashboard(){if(busy)return;busy=true;showLoading(true);try{const r=await fetch(SHEET_URL+(SHEET_URL.includes("?")?"&":"?")+"action=dashboard&v="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);const j=await r.json();if(!j.success)throw Error(j.message||"API tidak valid");setText("saldo",rupiah(j.saldo));setText("totalMasuk",rupiah(j.totalMasuk));setText("totalKeluar",rupiah(j.totalKeluar));renderKategori("rekapMasuk",j.kategoriMasuk,"rekapMasukTotal");renderKategori("rekapKeluar",j.kategoriKeluar,"rekapKeluarTotal");renderRecent(j.transaksiTerakhir);setText("lastUpdate",waktuFormatter.format(new Date()));document.getElementById("errorBox")?.classList.add("d-none")}catch(e){console.error(e);const b=document.getElementById("errorBox");if(b){b.textContent="Dashboard belum dapat mengambil data: "+e.message;b.classList.remove("d-none")}}finally{busy=false;showLoading(false)}}
document.addEventListener("DOMContentLoaded",()=>{loadDashboard();setInterval(loadDashboard,60000)});
